apiVersion: v1
kind: Service
metadata:
  name: clinica-svc
  labels:
    app.kubernetes.io/name: clinica
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: clinica-prod
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clinica
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: clinica-prod
  ports:
    - name: http
      port: 9091
      targetPort: 9091
      protocol: TCP
